### ISSUE TITLE
What version of unity is it?

### ISSUE THREAD

**Issue by DJ-Huang** [airliang/unity-raytracing#1]
I used 2022.3.8 and reported a lot of errors.

![image](https://github.com/airliang/unity-raytracing/assets/18584942/63c08263-6289-4dc5-bb59-9c1d365beafc)

**Comment by DJ-Huang** [comment]
Sorry I forgot to import the URP, But when I open the CornellBox Scene and run it, it fails to render and has this error:


![image](https://github.com/airliang/unity-raytracing/assets/18584942/0cd0481f-209a-4eb7-9e3a-16fb2ac7013f)

**Comment by airliang** [comment]
> Sorry I forgot to import the URP, But when I open the CornellBox Scene and run it, it fails to render and has this error:
> 
> ![image](https://user-images.githubusercontent.com/18584942/279737835-0cd0481f-209a-4eb7-9e3a-16fb2ac7013f.png)

Thank you for pointing out this issue. I will fix it as soon as possible. This is caused by the new version of unity. It requires a more strict rule of compiling the compute shader. And I will also erase the [Reload] attributes in the WavefrontResource.cs.

**Comment by airliang** [comment]
> Sorry I forgot to import the URP, But when I open the CornellBox Scene and run it, it fails to render and has this error:
> 
> ![image](https://user-images.githubusercontent.com/18584942/279737835-0cd0481f-209a-4eb7-9e3a-16fb2ac7013f.png)

Hi, I fixed this issue now and you can update to the lastest version. I recommend you use Unity2022.3.x. Thanks.

**Comment by DJ-Huang** [comment]
Thank you very much, it works fine now.
